#!/usr/bin/env python3
"""
Infinity Kingdom Bot - Main Entry Point
Automated grinding assistant for Infinity Kingdom

Usage:
    python main.py                  # Run with default settings
    python main.py --hours 4        # Run for 4 hours
    python main.py --task collect   # Run single task
    python main.py --setup          # Setup wizard
"""

import argparse
import sys
import os
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).parent
sys.path.insert(0, str(PROJECT_ROOT))


def parse_arguments():
    """Parse command line arguments"""
    parser = argparse.ArgumentParser(
        description='Infinity Kingdom Automation Bot',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python main.py                    Start bot with default settings
  python main.py --hours 4          Run for 4 hours then stop
  python main.py --task collect     Run single resource collection
  python main.py --config my.yaml   Use custom config file
  python main.py --debug            Enable debug logging
  python main.py --setup            Run setup wizard
        """
    )
    
    parser.add_argument(
        '--config', '-c',
        default='config/settings.yaml',
        help='Path to configuration file'
    )
    
    parser.add_argument(
        '--hours', '-t',
        type=float,
        default=None,
        help='Maximum runtime in hours (overrides config)'
    )
    
    parser.add_argument(
        '--task',
        choices=[
            'collect_resources',
            'gather_resources', 
            'daily_quests',
            'collect_mail',
            'alliance_help',
            'free_chests',
            'attack_gnomes',
            'train_troops',
            'research',
            'build_upgrade'
        ],
        help='Run a single task and exit'
    )
    
    parser.add_argument(
        '--debug', '-d',
        action='store_true',
        help='Enable debug logging'
    )
    
    parser.add_argument(
        '--setup',
        action='store_true',
        help='Run setup wizard'
    )
    
    parser.add_argument(
        '--screenshot',
        action='store_true',
        help='Take a screenshot and exit'
    )
    
    parser.add_argument(
        '--status',
        action='store_true',
        help='Show current game status and exit'
    )
    
    parser.add_argument(
        '--version', '-v',
        action='version',
        version='Infinity Kingdom Bot v1.0.0'
    )
    
    return parser.parse_args()


def run_setup_wizard():
    """Interactive setup wizard"""
    print("\n" + "=" * 60)
    print("  INFINITY KINGDOM BOT - SETUP WIZARD")
    print("=" * 60 + "\n")
    
    print("This wizard will help you configure the bot.\n")
    
    # Device type
    print("1. What type of device are you using?")
    print("   [1] Emulator (BlueStacks, LDPlayer, etc.)")
    print("   [2] Android device via ADB")
    device_choice = input("   Enter choice (1 or 2): ").strip()
    
    device_type = 'emulator' if device_choice == '1' else 'adb'
    
    if device_type == 'emulator':
        window_name = input("\n2. Enter emulator window name (default: BlueStacks): ").strip()
        window_name = window_name or 'BlueStacks'
    else:
        adb_host = input("\n2. Enter ADB host (default: 127.0.0.1): ").strip() or '127.0.0.1'
        adb_port = input("   Enter ADB port (default: 5555): ").strip() or '5555'
    
    # Resolution
    print("\n3. Enter screen resolution:")
    width = input("   Width (default: 1920): ").strip() or '1920'
    height = input("   Height (default: 1080): ").strip() or '1080'
    
    # Tasks
    print("\n4. Which tasks would you like to enable?")
    tasks = {
        'collect_resources': True,
        'gather_resources': True,
        'daily_quests': True,
        'collect_mail': True,
        'alliance_help': True,
        'free_chests': True,
        'auto_battle': False,
        'train_troops': True,
        'research': True,
        'build_upgrade': True,
    }
    
    for task_name in tasks:
        default = 'Y' if tasks[task_name] else 'N'
        choice = input(f"   {task_name}? [Y/n] (default: {default}): ").strip().lower()
        if choice:
            tasks[task_name] = choice in ['y', 'yes']
    
    # Generate config
    config = f"""# Infinity Kingdom Bot Configuration
# Generated by setup wizard

device:
  type: "{device_type}"
"""
    
    if device_type == 'emulator':
        config += f'  window_name: "{window_name}"\n'
    else:
        config += f"""  adb:
    host: "{adb_host}"
    port: {adb_port}
"""
    
    config += f"""  resolution:
    width: {width}
    height: {height}

tasks:
  enabled:
"""
    
    for task_name, enabled in tasks.items():
        config += f"    {task_name}: {'true' if enabled else 'false'}\n"
    
    config += """
timing:
  click_delay: 0.3
  action_delay: 1.0
  screen_load_delay: 2.0
  resource_collection_interval: 30
  quest_check_interval: 15

safety:
  max_runtime_hours: 8
  human_like_delays: true
  random_click_offset: 5
  pause_on_attack: true

logging:
  level: INFO
  file_logging: true
  console_logging: true
"""
    
    # Save config
    config_path = Path('config/settings.yaml')
    config_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(config_path, 'w') as f:
        f.write(config)
    
    print(f"\n✅ Configuration saved to {config_path}")
    print("\nYou can now run the bot with: python main.py")
    print("=" * 60 + "\n")


def take_screenshot():
    """Take a screenshot for debugging"""
    from src.screen_capture import ScreenCapture
    from src.logger import get_logger
    
    logger = get_logger()
    
    # Load minimal config
    config = {
        'device': {
            'type': 'emulator',
            'window_name': 'BlueStacks',
            'resolution': {'width': 1920, 'height': 1080}
        }
    }
    
    screen = ScreenCapture(config)
    filepath = screen.save_screenshot(directory="screenshots")
    
    if filepath:
        print(f"✅ Screenshot saved to: {filepath}")
    else:
        print("❌ Failed to capture screenshot")


def print_banner():
    """Print welcome banner"""
    banner = """
    ╔══════════════════════════════════════════════════════════╗
    ║                                                          ║
    ║     ██╗███╗   ██╗███████╗██╗███╗   ██╗██╗████████╗██╗   ║
    ║     ██║████╗  ██║██╔════╝██║████╗  ██║██║╚══██╔══╝╚██╗  ║
    ║     ██║██╔██╗ ██║█████╗  ██║██╔██╗ ██║██║   ██║    ╚██╗ ║
    ║     ██║██║╚██╗██║██╔══╝  ██║██║╚██╗██║██║   ██║    ██╔╝ ║
    ║     ██║██║ ╚████║██║     ██║██║ ╚████║██║   ██║   ██╔╝  ║
    ║     ╚═╝╚═╝  ╚═══╝╚═╝     ╚═╝╚═╝  ╚═══╝╚═╝   ╚═╝   ╚═╝   ║
    ║                                                          ║
    ║              KINGDOM BOT v1.0.0                          ║
    ║         Automated Grinding Assistant                     ║
    ║                                                          ║
    ╚══════════════════════════════════════════════════════════╝
    """
    print(banner)


def main():
    """Main entry point"""
    args = parse_arguments()
    
    # Handle setup wizard
    if args.setup:
        run_setup_wizard()
        return 0
    
    # Handle screenshot
    if args.screenshot:
        take_screenshot()
        return 0
    
    # Print banner
    print_banner()
    
    # Check if config exists
    config_path = Path(args.config)
    if not config_path.exists():
        print(f"⚠️  Config file not found: {config_path}")
        print("   Run 'python main.py --setup' to create one")
        print("   Or the bot will use default settings\n")
    
    # Import bot engine (after path setup)
    from src.bot_engine import BotEngine
    
    # Create bot instance
    try:
        bot = BotEngine(args.config)
    except Exception as e:
        print(f"❌ Failed to initialize bot: {e}")
        return 1
    
    # Handle debug mode
    if args.debug:
        bot.logger.logger.setLevel('DEBUG')
        bot.logger.info("Debug mode enabled")
    
    # Handle single task
    if args.task:
        print(f"\n🎯 Running single task: {args.task}\n")
        success = bot.run_single_task(args.task)
        return 0 if success else 1
    
    # Handle status check
    if args.status:
        status = bot.get_status()
        print("\n📊 Bot Status:")
        for key, value in status.items():
            print(f"   {key}: {value}")
        return 0
    
    # Run bot
    try:
        print("\n🚀 Starting bot...\n")
        print("   Press Ctrl+C to stop\n")
        bot.start(duration_hours=args.hours)
        return 0
    except KeyboardInterrupt:
        print("\n\n⚠️  Interrupted by user")
        bot.stop()
        return 0
    except Exception as e:
        print(f"\n❌ Error: {e}")
        bot.stop()
        return 1


if __name__ == '__main__':
    sys.exit(main())
